import { NextRequest, NextResponse } from 'next/server';
import { randomBytes } from 'crypto';
import { getSteamAppDetails, validateAppId } from "@/utils/steamAPI";
import { generateSteamManifest, formatManifest } from "@/utils/manifestGenerator";
import { generateLuaScript } from "@/utils/luaGenerator";

// Simple file storage that works without database
const fileStorage = new Map<string, any>();

export async function POST(request: NextRequest) {
  try {
    console.log('🚀 Simple Generate API called');
    
    const { appId, discordUserId, discordUsername } = await request.json();
    console.log(`📝 Processing request for App ID: ${appId}, User: ${discordUsername}`);

    // Validate input
    if (!validateAppId(appId)) {
      return NextResponse.json(
        { error: 'Invalid App ID' },
        { status: 400 }
      );
    }

    if (!discordUserId) {
      return NextResponse.json(
        { error: 'Discord user ID is required' },
        { status: 400 }
      );
    }

    // Fetch Steam app data
    const appData = await getSteamAppDetails(appId);
    console.log(`🎮 Fetched Steam data for: ${appData.name}`);

    // Generate files
    const manifest = generateSteamManifest(appData);
    const manifestJson = formatManifest(manifest);
    const luaScript = generateLuaScript(appData);
    console.log('📁 Generated manifest and Lua script');

    // Generate unique access key
    const accessKey = randomBytes(16).toString('hex');

    // Calculate expiration (24 hours from now)
    const expiresAt = new Date();
    expiresAt.setHours(expiresAt.getHours() + 24);

    // Store in memory storage
    const fileData = {
      id: Date.now().toString(),
      accessKey,
      discordUserId,
      discordUsername: discordUsername || null,
      steamAppId: appId,
      steamAppName: appData.name,
      manifestContent: manifestJson,
      luaContent: luaScript,
      manifestSize: manifestJson.length,
      luaSize: luaScript.length,
      expiresAt: expiresAt,
      createdAt: new Date()
    };

    fileStorage.set(accessKey, fileData);
    console.log(`💾 Stored file in memory with key: ${accessKey}`);

    // Create Steamtools-compatible files
    const steamtoolsManifest = {
      format: "steamtools",
      version: "1.0",
      appid: appData.appId,
      name: appData.name,
      manifest: {
        ...manifest,
        steamtools_metadata: {
          generated_by: "Steam Manifest Generator Bot",
          generated_at: new Date().toISOString(),
          compatible_with: "Steamtools v1.0+",
          export_format: "json"
        }
      }
    };

    const steamtoolsLua = {
      format: "steamtools",
      version: "1.0",
      appid: appData.appId,
      name: appData.name,
      content: `--[[
  Steamtools Compatible Lua Script
  Generated for: ${appData.name} (${appData.appId})
  Generated by: Steam Manifest Generator Bot
  Generated at: ${new Date().toISOString()}
  
  This script is compatible with Steamtools and can be imported
  directly into your Steamtools project.
]]\n\n${luaScript}`,
      metadata: {
        generated_by: "Steam Manifest Generator Bot",
        generated_at: new Date().toISOString(),
        compatible_with: "Steamtools v1.0+",
        language: "lua",
        encoding: "utf-8"
      }
    };

    console.log(`🎉 Successfully generated files for ${appData.name}`);

    return NextResponse.json({
      success: true,
      accessKey: accessKey,
      downloadUrl: `/download/${accessKey}`,
      steamtoolsUrl: `/api/download/${accessKey}`,
      appId: appId,
      appName: appData.name,
      storage: 'memory',
      message: 'Files generated successfully',
      steamtoolsFiles: {
        manifest: steamtoolsManifest,
        lua: steamtoolsLua
      }
    });

  } catch (error: any) {
    console.error('❌ Error generating files:', error);
    return NextResponse.json(
      { error: 'Failed to generate files: ' + error.message },
      { status: 500 }
    );
  }
}

// Export storage for use in download route
export { fileStorage };
